blank_issues_enabled: true
contact_links:
  - name: PythOS Discussions (PythOS Repository)
    url: https://github.com/Captain-Awesome-Jnr/PythOS/discussions/
    about: Please ask and answer questions here.
